fiscozen/design_system

- packages/icon-button/src/FzIconButton.vue
- packages/icon-button/src/index.ts
- packages/icons/package.json
- packages/icons/src/FzIcon.vue
- packages/icons/src/index.ts
- packages/icons/src/types.ts
ho spostato su questo branch le modifiche di formattazione rispetto agli altri file della pr
https://github.com/fiscozen/design_system/pull/6
> refactor: automatic formatting

- apps/storybook/package.json
- apps/storybook/src/stories/Badge.stories.ts
- packages/badge/README.md
- packages/badge/package.json
- packages/badge/src/FzBadge.vue
- packages/badge/src/__tests__/FzBadge.spec.ts
- packages/badge/src/__tests__/__snapshots__/FzBadge.spec.ts.snap
- packages/badge/src/index.ts
- packages/badge/tsconfig.json
- packages/badge/vite.config.ts
- packages/badge/vitest.config.ts
- pnpm-lock.yaml
Jira: [LIB-274](https://fiscozen.atlassian.net/browse/LIB-274)
> feat(LIB-274): init badge component

- apps/storybook/package.json
- apps/storybook/src/stories/ViewFlag.stories.ts
- packages/view-flag/README.md
- packages/view-flag/package.json
- packages/view-flag/src/FzViewFlag.vue
- packages/view-flag/src/__tests__/FzViewFlag.spec.ts
- packages/view-flag/src/__tests__/__snapshots__/FzViewFlag.spec.ts.snap
- packages/view-flag/src/index.ts
- packages/view-flag/tsconfig.json
- packages/view-flag/vite.config.ts
- packages/view-flag/vitest.config.ts
- pnpm-lock.yaml
Jira: [LIB-271](https://fiscozen.atlassian.net/browse/LIB-271)
> feat(LIB-271): init view-flag component

- packages/navlist/src/FzNavlist.vue
[Jira](https://fiscozen.atlassian.net/browse/LIB-299)
> LIB-299 fix(navlist): subitems font style

- packages/navlink/src/FzNavlink.vue
[Jira](https://fiscozen.atlassian.net/browse/LIB-300)
> LIB-300 fix(navlink): font weight

- packages/view-flag/src/FzViewFlag.vue
[Jira](https://fiscozen.atlassian.net/browse/LIB-298)
> LIB-298 fix(viewflag): text alignment

- docs/RFC/TEMPLATE.md
- docs/RFC/navbar/2024-03-26.md
[Jira](https://fiscozen.atlassian.net/browse/LIB-279)
Moving the old RFC from the knowledge base private repo to the design system public repo
> LIB-279 docs(navbar): moving RFC inside design sytem repo

- docs/RFC/topbar/2024-05-07.md
Jira: [LIB-391](https://fiscozen.atlassian.net/browse/LIB-391)
> LIB-391 docs(topbar): add RFC

- docs/RFC/tab/2024-05-06.md
Jira: [LIB-389](https://fiscozen.atlassian.net/browse/LIB-389)
> Lib 389 rfc tab

- docs/RFC/tooltip/2024-05-17.md
[Jira](https://fiscozen.atlassian.net/browse/LIB-405)
I decided to make this RFC smaller because most of the logic about positioning is handled by the more generic `useFloating` composable.
Therefore I will create a separate documentation file for that
> LIB-405 docs(tooltip): rfc

- apps/storybook/package.json
- apps/storybook/src/stories/Link.stories.ts
- packages/link/.eslintrc.cjs
- packages/link/.prettierrc.js
- packages/link/README.md
- packages/link/package.json
- packages/link/src/FzLink.vue
- packages/link/src/__tests__/FzLink.spec.ts
- packages/link/src/__tests__/__snapshots__/FzLink.spec.ts.snap
- packages/link/src/index.ts
- packages/link/tsconfig.json
- packages/link/vite.config.ts
- packages/link/vitest.config.ts
- pnpm-lock.yaml
Jira: [LIB-394](https://fiscozen.atlassian.net/browse/LIB-394)
> feat(LIB-394): add Link component

- apps/storybook/src/stories/Tab.stories.ts
- packages/tab/package.json
- packages/tab/src/FzTab.vue
- packages/tab/src/FzTabs.vue
- packages/tab/src/__test__/FzTabs.test.ts
Jira: [LIB-460](https://fiscozen.atlassian.net/browse/LIB-460)
I was unable to handle the FzTab created by the v-for directive. This fix should solve this use case.
> Lib 460 hotfix vfor slots tab

- docs/RFC/radio/2024-05-21.md
Jira: [LIB-435](https://fiscozen.atlassian.net/browse/LIB-435)
> feat(LIB-435): rfc for radio and radiogroup

- docs/RFC/checkbox/2024-05-20.md
Jira: [LIB-433](https://fiscozen.atlassian.net/browse/LIB-433)
> feat(LIB-433): add rfc checkbox

- docs/RFC/dialog/2024-05-21.md
[Jira](https://fiscozen.atlassian.net/browse/LIB-445)
> LIB-445 docs: dialog RFC

- docs/RFC/checkbox/2024-05-28.md
Jira: [LIB-449](https://fiscozen.atlassian.net/browse/LIB-449)
> feat(LIB-449): RFC checkbox group

- apps/storybook/src/stories/Tab.stories.ts
- packages/tab/package.json
- packages/tab/src/FzTabs.vue
- packages/tab/src/__test__/__snapshots__/FzTabs.test.ts.snap
Jira: [LIB-477](https://fiscozen.atlassian.net/browse/LIB-477)
> fix(LIB-477): fix slot tabs-end and new tabs-content-ends

- apps/storybook/package.json
- apps/storybook/src/stories/Topbar.stories.ts
- packages/composables/src/FzFloating.vue
- packages/composables/src/composables/index.ts
- packages/composables/src/composables/useBreakpoints.ts
- packages/composables/src/composables/useFloating.ts
- packages/composables/src/composables/useMediaQuery.ts
- packages/composables/src/utils/index.ts
- packages/style/package.json
- packages/style/src/constants.ts
- packages/style/src/index.ts
- packages/topbar/.eslintrc.cjs
- packages/topbar/.prettierrc.js
- packages/topbar/README.md
- packages/topbar/package.json
- packages/topbar/src/FzTopbar.vue
- packages/topbar/src/__tests__/FzTopbar.spec.ts
- packages/topbar/src/__tests__/__snapshots__/FzAvatar.spec.ts.snap
- packages/topbar/src/__tests__/__snapshots__/FzTopbar.spec.ts.snap
- packages/topbar/src/index.ts
- packages/topbar/tsconfig.json
- packages/topbar/vite.config.ts
- packages/topbar/vitest.config.ts
- pnpm-lock.yaml
Jira: [LIB-392](https://fiscozen.atlassian.net/browse/LIB-392)
> feat(LIB-392): init topbar component

- apps/storybook/package.json
- apps/storybook/src/stories/Radio.stories.ts
- apps/storybook/src/stories/RadioGroup.stories.ts
- apps/storybook/tailwind.config.js
- docs/RFC/radio/2024-05-21.md
- packages/radio/README.md
- packages/radio/package.json
- packages/radio/src/FzRadio.vue
- packages/radio/src/FzRadioGroup.vue
- packages/radio/src/__test__/FzRadio.test.ts
- packages/radio/src/__test__/FzRadioGroup.test.ts
- packages/radio/src/__test__/__snapshots__/FzRadio.test.ts.snap
- packages/radio/src/__test__/__snapshots__/FzRadioGroup.test.ts.snap
- packages/radio/src/common.ts
- packages/radio/src/components/FzRadioErrorText.vue
- packages/radio/src/index.ts
- packages/radio/src/types.ts
- packages/radio/tsconfig.json
- packages/radio/vite.config.ts
- packages/radio/vitest.config.ts
- pnpm-lock.yaml
Jira: [LIB-436](https://fiscozen.atlassian.net/browse/LIB-436)
> feat(LIB-436): radio and radio group components

- docs/RFC/button/2024-06-03.md
- docs/RFC/checkbox/2024-05-20.md
Jira: [LIB-472](https://fiscozen.atlassian.net/browse/LIB-472)
> feat(LIB-472): RFC Button Group

- docs/RFC/select/2024-06-07.md
Jira: [LIB-474](https://fiscozen.atlassian.net/browse/LIB-474)
> feat(LIB-474): rfc select

- docs/RFC/card/2024-06-03.md
Jira: [LIB-467](https://fiscozen.atlassian.net/browse/LIB-467)
> feat(LIB-467): rfc card

- docs/RFC/dropdown/2024-05-07.md
Jira: [LIB-441](https://fiscozen.atlassian.net/browse/LIB-441)
> LIB-441 docs(dropdown): add rfc

- packages/button/src/__tests__/__snapshots__/FzIconButtton.spec.ts.snap
- packages/collapse/src/__tests__/__snapshots__/FzCollapse.spec.ts.snap
- packages/composables/src/__tests__/__snapshots__/FzFloating.spec.ts.snap
- packages/dialog/src/__test__/__snapshots__/FzDialog.test.ts.snap
- packages/navbar/src/__tests__/__snapshots__/FzNavbar.spec.ts.snap
- packages/navlink/src/__tests__/__snapshots__/FzNavlink.spec.ts.snap
- packages/navlist/src/__tests__/__snapshots__/FzNavlist.spec.ts.snap
- packages/tooltip/src/__tests__/__snapshots__/FzTooltip.spec.ts.snap
- packages/view-flag/src/__tests__/__snapshots__/FzViewFlag.spec.ts.snap
@Crish15 @Trebh Ci sono diversi test che falliscono a causa di snapshot non aggiornati. Fatemi sapere se vi tornano gli aggiornamenti.
> test: update all snapshots causing tests to fail

- apps/storybook/package.json
- apps/storybook/src/stories/Checkbox.stories.ts
- apps/storybook/src/stories/CheckboxGroup.stories.ts
- packages/checkbox/README.md
- packages/checkbox/package.json
- packages/checkbox/src/FzCheckbox.vue
- packages/checkbox/src/FzCheckboxGroup.vue
- packages/checkbox/src/__test__/FzCheckbox.test.ts
- packages/checkbox/src/__test__/FzCheckboxGroup.test.ts
- packages/checkbox/src/__test__/__snapshots__/FzCheckbox.test.ts.snap
- packages/checkbox/src/common.ts
- packages/checkbox/src/components/FzCheckboxErrorText.vue
- packages/checkbox/src/components/FzCheckboxGroupOption.vue
- packages/checkbox/src/index.ts
- packages/checkbox/src/types.ts
- packages/checkbox/tsconfig.json
- packages/checkbox/vite.config.ts
- packages/checkbox/vitest.config.ts
- packages/icons/package.json
- pnpm-lock.yaml
Jira: [LIB-434](https://fiscozen.atlassian.net/browse/LIB-434)
> feat(LIB-434): checkbox and checkbox group

- docs/RFC/alert/2024-06-13.md
Jira: [LIB-443](https://fiscozen.atlassian.net/browse/LIB-443)
> LIB-443 docs(alert): add rfc

- apps/storybook/package.json
- apps/storybook/src/stories/Alert.stories.ts
- packages/alert/.eslintrc.cjs
- packages/alert/.prettierrc.js
- packages/alert/README.md
- packages/alert/package.json
- packages/alert/src/FzAlert.vue
- packages/alert/src/__tests__/FzAlert.spec.ts
- packages/alert/src/__tests__/__snapshots__/FzAlert.spec.ts.snap
- packages/alert/src/index.ts
- packages/alert/src/types.ts
- packages/alert/tsconfig.json
- packages/alert/vite.config.ts
- packages/alert/vitest.config.ts
- packages/icons/package.json
- pnpm-lock.yaml
Jira: [LIB-443](https://fiscozen.atlassian.net/browse/LIB-443)
> LIB-443 feat(alert): add component

- packages/alert/src/FzAlert.vue
- packages/alert/src/__tests__/__snapshots__/FzAlert.spec.ts.snap
Jira: [LIB-444](https://fiscozen.atlassian.net/browse/LIB-444)
> LIB-444 fix(alert): remove background from simple style, adapt width

- packages/tab/package.json
- packages/tab/src/__test__/__snapshots__/FzTabs.test.ts.snap
- packages/tab/src/common.ts
- packages/tab/src/components/FzTabName.vue
- packages/tab/src/components/FzTabPicker.vue
- packages/tab/src/components/FzTabPickerValue.vue
Jira: [LIB-487](https://fiscozen.atlassian.net/browse/LIB-487)
> fix(LIB-487): updated border radius for tabs

- packages/radio/package.json
- packages/radio/src/FzRadio.vue
Some fix I made to make the radio work for ticket [LIB-491](https://fiscozen.atlassian.net/browse/LIB-491)
> fix id and label for not unique

- apps/storybook/src/stories/Alert.stories.ts
- packages/alert/package.json
- packages/alert/src/FzAlert.vue
- packages/alert/src/__tests__/FzAlert.spec.ts
- packages/alert/src/__tests__/__snapshots__/FzAlert.spec.ts.snap
- packages/alert/src/types.ts
- pnpm-lock.yaml
Jira: [LIB-517](https://fiscozen.atlassian.net/browse/LIB-517)
> LIB-517 feat(alert): add link as cta

- package.json
- plopfile.js
- pnpm-lock.yaml
- templates/component/.eslintrc.cjs
- templates/component/.prettierrc.js
- templates/component/README.md
- templates/component/package.json
- templates/component/src/FzComponent.vue
- templates/component/src/__tests__/FzComponent.spec.ts
- templates/component/src/index.ts
- templates/component/src/story.ts
- templates/component/src/types.ts
- templates/component/tsconfig.json
- templates/component/vite.config.ts
- templates/component/vitest.config.ts
Jira: [LIB-515](https://fiscozen.atlassian.net/browse/LIB-515)
> feat(LIB-515): add generate:component command

- packages/icons/package.json
> fix icon version

- packages/select/package.json
- packages/select/src/FzSelect.vue
- packages/select/src/components/FzSelectOption.vue
Some fixes in order to make the select works as expected in our main application
> fix: some fixes for lib-501

- plopfile.js
Jira: [LIB-556](https://fiscozen.atlassian.net/browse/LIB-556)
> LIB-556 fix(generator): add missing tsconfig generation

- packages/button/package.json
- packages/icons/package.json
- pnpm-lock.yaml
[Jira](https://fiscozen.atlassian.net/browse/LIB-558)
> LIB-558(icons): update icons and button for publish

- packages/actionlist/package.json
- packages/actionlist/src/FzActionlist.vue
- packages/dropdown/package.json
- packages/dropdown/src/FzDropdown.vue
Jira: [LIB-554](https://fiscozen.atlassian.net/browse/LIB-554)
> LIB-554 feat(dropdown): add click outside

- apps/storybook/src/stories/RadioGroup.stories.ts
- packages/radio/package.json
- packages/radio/src/FzRadio.vue
- packages/radio/src/__test__/__snapshots__/FzRadio.test.ts.snap
- packages/radio/src/__test__/__snapshots__/FzRadioGroup.test.ts.snap
- packages/radio/src/common.ts
- packages/radio/src/components/FzRadioErrorText.vue
fix for Jira: [(LIB-491)](https://fiscozen.atlassian.net/browse/(LIB-491))
> Fix(LIB-491): design radio 

- apps/storybook/src/stories/Card.stories.ts
- packages/card/package.json
- packages/card/src/FzCard.vue
- packages/card/src/types.ts
Jira: [LIB-523](https://fiscozen.atlassian.net/browse/LIB-523)
> fix(LIB-523): FzCard fixes for production app

- apps/storybook/src/stories/RadioGroup.stories.ts
- packages/radio/package.json
- packages/radio/src/FzRadio.vue
Jira: [LIB-569](https://fiscozen.atlassian.net/browse/LIB-569)
> fix(LIB-569) fix radio on change event firing at creation

- apps/storybook/package.json
- apps/storybook/src/stories/Icon.stories.ts
- packages/icons/package.json
- pnpm-lock.yaml
I have created a story in which there is a list of all the icons currently available. The page is still in an early stage with poor graphics, but I think it is useful for our developers to easily find what they can use.
> Add icon list story with all the current icons

- plopfile.js
I've changed the regex in order to contemplate sentence case/title case (spaces), while maintaining camelCase, PascalCase, kebab-case support.
> fix(plop): kebabize contemplates spaces

- apps/storybook/src/stories/Button.stories.ts
- packages/button/package.json
- packages/button/src/FzButton.vue
Jira: [LIB-571](https://fiscozen.atlassian.net/browse/LIB-571)
> fix(LIB-571): button text ellipsis overflow

- apps/storybook/package.json
- apps/storybook/src/stories/Textarea.stories.ts
- packages/textarea/README.md
- packages/textarea/eslintrc.cjs
- packages/textarea/package.json
- packages/textarea/prettierrc.js
- packages/textarea/src/FzTextarea.vue
- packages/textarea/src/__tests__/FzTextarea.spec.ts
- packages/textarea/src/__tests__/__snapshots__/FzTextarea.spec.ts.snap
- packages/textarea/src/index.ts
- packages/textarea/src/types.ts
- packages/textarea/tsconfig.json
- packages/textarea/vite.config.ts
- packages/textarea/vitest.config.ts
- pnpm-lock.yaml
Jira: [LIB-583](https://fiscozen.atlassian.net/browse/LIB-583)
> LIB-583 feat(textarea): add FzTextarea

- packages/link/package.json
- packages/link/src/FzLink.vue
- packages/link/src/__tests__/FzLink.spec.ts
- packages/link/src/index.ts
- packages/link/src/types.ts
Jira: [LIB-596](https://fiscozen.atlassian.net/browse/LIB-596)
> LIB-596 feat(link): add target prop

- apps/storybook/package.json
- apps/storybook/src/stories/SimpleTable.stories.ts
- packages/simple-table/README.md
- packages/simple-table/eslintrc.cjs
- packages/simple-table/package.json
- packages/simple-table/prettierrc.js
- packages/simple-table/src/FzColumn.vue
- packages/simple-table/src/FzSimpleTable.vue
- packages/simple-table/src/__tests__/FzSimpleTable.spec.ts
- packages/simple-table/src/__tests__/__snapshots__/FzSimpleTable.spec.ts.snap
- packages/simple-table/src/index.ts
- packages/simple-table/src/types.ts
- packages/simple-table/tsconfig.json
- packages/simple-table/vite.config.ts
- packages/simple-table/vitest.config.ts
- pnpm-lock.yaml
Jira: [LIB-594](https://fiscozen.atlassian.net/browse/LIB-594)
> LIB-594 feat(simple-table): add FzSimpleTable

- packages/alert/package.json
- packages/alert/src/FzAlert.vue
- packages/alert/src/__tests__/FzAlert.spec.ts
- packages/alert/src/__tests__/__snapshots__/FzAlert.spec.ts.snap
- packages/alert/src/types.ts
Jira: [LIB-595](https://fiscozen.atlassian.net/browse/LIB-595)
> LIB-595 feat(alert): add linkActionTarget prop

- packages/dropdown/package.json
- packages/dropdown/src/FzDropdown.vue
- packages/dropdown/src/__tests__/__snapshots__/FzDropdown.spec.ts.snap
- packages/dropdown/src/index.ts
- packages/dropdown/src/types.ts
Jira: [LIB-592](https://fiscozen.atlassian.net/browse/LIB-592)
- Added slot to override button opener
- Added openerDisabled prop
- Added openerClass prop
> LIB-592 feat(dropdown): add opener slot, add button props

- packages/button/package.json
- packages/button/src/FzButton.vue
- packages/button/src/FzIconButton.vue
Jira: [LIB-603](https://fiscozen.atlassian.net/browse/LIB-603)
> LIB-603 fix(button): dont truncate for icon-button

- packages/dropdown/src/types.ts
Jira: [LIB-599](https://fiscozen.atlassian.net/browse/LIB-599)
> LIB-599 fix(dropdown): make size prop's type optional

- packages/actionlist/package.json
- packages/actionlist/src/FzActionlist.vue
- packages/composables/package.json
- packages/composables/src/FzFloating.vue
- packages/composables/src/composables/useFloating.ts
- packages/composables/src/types.ts
- packages/dropdown/src/FzDropdown.vue
Jira: [LIB-598](https://fiscozen.atlassian.net/browse/LIB-598)
> LIB-598 fix(dropdown): fix double background caused by conflict with FzFloating

- packages/dialog/package.json
- packages/dialog/src/FzConfirmDialog.vue
- packages/dialog/src/__test__/__snapshots__/FzDialog.test.ts.snap
Jira: [LIB-604](https://fiscozen.atlassian.net/browse/LIB-604)
> LIB-604 fix(confirm-dialog): change close button icon name

- apps/storybook/src/stories/ConfirmDialog.stories.ts
- packages/dialog/src/FzConfirmDialog.vue
- packages/dialog/src/FzDialog.vue
- packages/dialog/src/types.ts
Jira: [LIB-607](https://fiscozen.atlassian.net/browse/LIB-607)
> LIB-607 feat(confirm-dialog): add confirmButtonVariant prop

- apps/storybook/src/stories/Select.stories.ts
- packages/select/package.json
- packages/select/src/FzSelect.vue
- packages/select/src/components/FzSelectOption.vue
- packages/select/src/types.ts
Jira: [LIB-584](https://fiscozen.atlassian.net/browse/LIB-584)
I created an automatic mechanism to calculate the maximum height based on the position of the container.
I also introduced a new `floatingPanelMaxHeight` props to cover as many use cases as possible.
> fix(LIB-584): max height for floating panel

- packages/toast/src/FzToastQueue.vue
- packages/toast/src/queue.ts
- packages/toast/src/types.ts
Jira: [LIB-605](https://fiscozen.atlassian.net/browse/LIB-605)
> LIB-605 fix(alert): replaced createdAt as id with a true id

- apps/storybook/src/stories/ToastQueue.stories.ts
- packages/toast/package.json
- packages/toast/src/FzToastQueue.vue
- packages/toast/src/types.ts
Jira: [LIB-636](https://fiscozen.atlassian.net/browse/LIB-636)
> LIB-636 feat(toast): open stack when new toast is enqueued

- packages/composables/package.json
- packages/composables/src/composables/useClickOutside.ts
- packages/dialog/package.json
- packages/dialog/src/FzDialog.vue
- pnpm-lock.yaml
Jira: [LIB-654](https://fiscozen.atlassian.net/browse/LIB-654)
> LIB-654 refactor(dialog): backdrop click logic

- packages/select/package.json
- packages/select/src/FzSelect.vue
- packages/select/src/components/FzSelectOption.vue
Jira: [LIB-657](https://fiscozen.atlassian.net/browse/LIB-657)
> fix(LIB-657): add type button to all button tag

- packages/select/package.json
- packages/select/src/FzSelect.vue
Now it should close the floating panel when selecting an option
> fix close on click

- apps/storybook/package.json
- packages/icons/package.json
- pnpm-lock.yaml
Jira: [LIB-656](https://fiscozen.atlassian.net/browse/LIB-656)
> feat(LIB-656):update icons list

- packages/composables/src/composables/useClickOutside.ts
[Jira](https://fiscozen.atlassian.net/browse/LIB-672)
> LIB-672 fix(composables): useClickOutside document fallback

- apps/storybook/src/stories/SimpleTable.stories.ts
Jira: [LIB-674](https://fiscozen.atlassian.net/browse/LIB-674)
> LIB-674 feat(simple-table): add FzColumn as subcomponent

- apps/storybook/src/stories/Typeahead.stories.ts
- packages/typeahead/package.json
- packages/typeahead/src/FzTypeahead.vue
- packages/typeahead/src/types.ts
- packages/typeahead/src/utils.ts
Jira: [LIB-690](https://fiscozen.atlassian.net/browse/LIB-690)
> Lib 690 fix typeahead input event

- apps/storybook/src/stories/Datepicker.stories.ts
- packages/datepicker/package.json
- packages/datepicker/src/FzDatepicker.vue
- packages/datepicker/src/types.ts
Jira: [LIB-724](https://fiscozen.atlassian.net/browse/LIB-724)
> feat(FzDatepicker): convert datepicker value into string

- apps/storybook/src/stories/Datepicker.stories.ts
- packages/datepicker/package.json
- packages/datepicker/src/FzDatepicker.vue
Jira: [LIB-731](https://fiscozen.atlassian.net/browse/LIB-731)
> LIB-731 fix(datepicker): pass name prop to input

- apps/storybook/src/stories/CurrencyInput.stories.ts
- packages/composables/package.json
- packages/composables/src/composables/useCurrency.ts
- packages/input/package.json
- packages/input/src/FzCurrencyInput.vue
- packages/input/src/types.ts
Jira: [LIB-793](https://fiscozen.atlassian.net/browse/LIB-793)
> feat(LIB-793): add nullOnEmpty for FzCurrencyInput

- packages/composables/package.json
- packages/composables/src/FzFloating.vue
Jira: [LIB-725](https://fiscozen.atlassian.net/browse/LIB-725)
> LIB-725 fix(composables): remove duplicate classes

- apps/storybook/src/stories/Tokens.stories.ts
You can see it in action here: https://65e5d7f524a5908cb4d75bd7-onxddhnydu.chromatic.com/?path=/docs/tokens--docs
> Token Story page

- packages/checkbox/package.json
- packages/checkbox/src/FzCheckbox.vue
Jira: [LIB-818](https://fiscozen.atlassian.net/browse/LIB-818)
> fix(LIB-818): fix checkbox hidden input style

- apps/storybook/package.json
- apps/storybook/src/stories/Divider.stories.ts
- apps/storybook/tailwind.config.js
- packages/divider/README.md
- packages/divider/eslintrc.cjs
- packages/divider/package.json
- packages/divider/prettierrc.js
- packages/divider/src/FzDivider.vue
- packages/divider/src/__tests__/FzDivider.spec.ts
- packages/divider/src/__tests__/__snapshots__/FzDivider.spec.ts.snap
- packages/divider/src/index.ts
- packages/divider/src/types.ts
- packages/divider/tsconfig.json
- packages/divider/vite.config.ts
- packages/divider/vitest.config.ts
- pnpm-lock.yaml
Jira: [LIB-702](https://fiscozen.atlassian.net/browse/LIB-702)
> LIB-702 feat(divider): first working version

- packages/select/src/__test__/FzSelect.spec.ts
Jira: [LIB-800](https://fiscozen.atlassian.net/browse/LIB-800)
> fix(LIB-800): fix broken tests

- packages/checkbox/package.json
- packages/checkbox/src/FzCheckbox.vue
- packages/checkbox/src/__test__/FzCheckbox.test.ts
Jira: [LIB-823](https://fiscozen.atlassian.net/browse/LIB-823)
> fix(LIB-823): handle undefined and null on v-model

- packages/input/package.json
- packages/input/src/FzCurrencyInput.vue
Jira: [LIB-797](https://fiscozen.atlassian.net/browse/LIB-797)
> LIB-797 feat(input): expose inputRef

- apps/storybook/src/stories/CurrencyInput.stories.ts
- packages/composables/package.json
- packages/composables/src/composables/useCurrency.ts
- packages/input/src/__tests__/FzCurrencyInput.spec.ts
Jira: [LIB-832](https://fiscozen.atlassian.net/browse/LIB-832)
> LIB-832 fix(composable): usecurrency 0 amount handling

- apps/storybook/package.json
- apps/storybook/src/stories/Icon.stories.ts
- packages/icons/package.json
- pnpm-lock.yaml
Jira: [LIB-834](https://fiscozen.atlassian.net/browse/LIB-834)
> Feat(lib 834) new icon

- apps/storybook/src/stories/Link.stories.ts
- packages/link/package.json
- packages/link/src/FzLink.vue
- packages/link/src/types.ts
Jira: [LIB-807](https://fiscozen.atlassian.net/browse/LIB-807)
> Feat(LIB-807): FzLink External Link

- packages/dialog/package.json
- packages/dialog/src/FzDialog.vue
https://fiscozen.atlassian.net/browse/SQB-1661
> hotfix: changed max size to dynamic max size

- packages/dialog/package.json
- packages/dialog/src/FzConfirmDialog.vue
- packages/dialog/src/types.ts
Jira: [LIB-846](https://fiscozen.atlassian.net/browse/LIB-846)
> LIB-846 feat(dialog): add doesCancelButtonCloseDialog and doesConfirmButtonCloseDialog

- apps/storybook/src/stories/Alert.stories.ts
- packages/alert/package.json
- packages/alert/src/FzAlert.vue
- packages/alert/src/__tests__/FzAlert.spec.ts
- packages/alert/src/types.ts
Jira: [LIB-778](https://fiscozen.atlassian.net/browse/LIB-778)
> feat(LIB-778): add external props to FzAlert

- apps/storybook/src/stories/Datepicker.stories.ts
- packages/datepicker/package.json
- packages/datepicker/src/FzDatepicker.vue
Enabled autoPosition by default
> fix(datepicker): calendar position

- packages/composables/package.json
- packages/composables/src/composables/useCurrency.ts
- packages/composables/src/types.ts
- packages/input/package.json
- packages/input/src/FzCurrencyInput.vue
- packages/input/src/FzInput.vue
- packages/input/src/__tests__/FzCurrencyInput.spec.ts
- packages/input/src/types.ts
Jira: [LIB-1293](https://fiscozen.atlassian.net/browse/LIB-1293)
> release(input): 0.1.8

- packages/button/package.json
- packages/button/src/FzButton.vue
Jira: [LIB-1303](https://fiscozen.atlassian.net/browse/LIB-1303)
> LIB-1303 fix(button): pass iconVariant to Icon

- packages/composables/package.json
- packages/composables/src/types.ts
Jira: [LIB-680](https://fiscozen.atlassian.net/browse/LIB-680)
> fix(composables): make isOpen prop optional

- apps/storybook/src/stories/Link.stories.ts
- packages/link/package.json
- packages/link/src/FzLink.vue
- packages/link/src/types.ts
Jira: [LIB-1307](https://fiscozen.atlassian.net/browse/LIB-1307)
> fix(link): rename link 'style' param to 'linkStyle'

- apps/storybook/src/stories/Link.stories.ts
- packages/link/package.json
- packages/link/src/FzLink.vue
- packages/link/src/types.ts
Jira: [???](https://fiscozen.atlassian.net/browse/???)
> Release/link 0.1.3

- apps/storybook/src/stories/Icon.stories.ts
Jira: [LIB-1314](https://fiscozen.atlassian.net/browse/LIB-1314)
> fix(icon): fix variant and size params of stories

- apps/storybook/src/stories/Navlist.stories.ts
- packages/navlist/package.json
- packages/navlist/src/FzNavlist.vue
- packages/navlist/src/__tests__/FzNavlist.spec.ts
- packages/navlist/src/__tests__/__snapshots__/FzNavlist.spec.ts.snap
- packages/navlist/src/types.ts
- pnpm-lock.yaml
Jira: [Lib 1316](https://fiscozen.atlassian.net/browse/LIB-1316)
> LIB-1316 fix(navlist): support FzRouterNavlink

- apps/storybook/src/stories/ConfirmDialog.stories.ts
- packages/composables/package.json
- packages/composables/src/composables/useClickOutside.ts
- packages/dialog/package.json
- packages/dialog/src/FzConfirmDialog.vue
- packages/dialog/src/FzDialog.vue
- packages/dialog/src/types.ts
Jira: [LIB-1290](https://fiscozen.atlassian.net/browse/LIB-1290)
> LIB-1290 feat(dialog): add shouldAlwaysRender prop

- apps/storybook/src/stories/Datepicker.stories.ts
- packages/datepicker/package.json
- packages/datepicker/src/FzDatepicker.vue
- packages/datepicker/src/__tests__/__snapshots__/FzDatepicker.spec.ts.snap
- packages/datepicker/src/types.ts
Jira: [LIB-1304](https://fiscozen.atlassian.net/browse/LIB-1304)
> Release/datepicker 0.1.10

- packages/badge/package.json
- packages/badge/src/FzBadge.vue
- packages/badge/src/__tests__/__snapshots__/FzBadge.spec.ts.snap
Jira: [LIB-1338](https://fiscozen.atlassian.net/browse/LIB-1338)
> LIB-1338 fix(badge): update height

- apps/storybook/package.json
- packages/icons/package.json
- pnpm-lock.yaml
Jira: [LIB-1341](https://fiscozen.atlassian.net/browse/LIB-1341)
> feat(LIB-1341): update of FzIcon with newer icons

- apps/storybook/src/stories/Select.stories.ts
- packages/select/package.json
- packages/select/src/FzSelect.vue
- packages/select/src/__test__/FzSelect.spec.ts
- packages/select/src/common.ts
Jira: [LIB-1268](https://fiscozen.atlassian.net/browse/LIB-1268)
> fix(LIB-1268): fix larghezza fzselect e floating opening

- apps/storybook/src/stories/Upload.stories.ts
- packages/upload/package.json
- packages/upload/src/FzUpload.vue
- packages/upload/src/__tests__/FzUpload.spec.ts
- packages/upload/src/__tests__/__snapshots__/FzUpload.spec.ts.snap
Jira: [LIB-1340](https://fiscozen.atlassian.net/browse/LIB-1340)
> feat(LIB-1340): Handle singlefile in FzUpload

- packages/dialog/package.json
- packages/dialog/src/FzDialog.vue
- pnpm-lock.yaml
Jira: [LIB-1356](https://fiscozen.atlassian.net/browse/LIB-1356)
> LIB-1356 feat(dialog): add dialog-polyfill

- packages/dialog/package.json
- packages/dialog/src/FzDialog.vue
Jira: [LIB-1356](https://fiscozen.atlassian.net/browse/LIB-1356)
> LIB-1356 fix(dialog): add max-height fallback to dvh support

- apps/storybook/src/stories/CurrencyInput.stories.ts
- packages/composables/src/composables/useCurrency.ts
- packages/composables/src/composables/useFloating.ts
- packages/composables/src/types.ts
Expose the option only for formatting purposes
> feat(composables): expose usegrouping option

- packages/dialog/package.json
- packages/dialog/src/FzDialog.vue
- packages/style/tailwind.config.js
Jira: [LIB-1366](https://fiscozen.atlassian.net/browse/LIB-1366)
Before:
After:
> LIB-1366 fix(dialog): refactor dialog sizing with dynamic fallback to dvh

- apps/storybook/src/stories/Select.stories.ts
- apps/storybook/tailwind.config.js
- packages/select/package.json
- packages/select/src/FzSelect.vue
- packages/select/src/__test__/FzSelect.spec.ts
- packages/select/src/components/FzSelectLabel.vue
- packages/select/src/components/FzSelectOption.vue
- packages/select/src/types.ts
Jira: [LIB-1360](https://fiscozen.atlassian.net/browse/LIB-1360)
> feat(LIB-1360): add Label on FzSelect

- packages/navbar/package.json
- packages/navbar/src/FzNavbar.vue
- packages/navbar/src/types.ts
Adds a click event emitter for the mobile menu button
> feat(navbar): add event emitter menuButtonClick

- packages/collapse/package.json
- packages/collapse/src/FzCollapse.vue
Jira: [LIB-1457](https://fiscozen.atlassian.net/browse/LIB-1457)
> LIB-1457 fix(collapse): remove native arrow icon on webkit

- packages/navbar/package.json
- packages/navbar/src/FzNavbar.vue
- packages/navbar/src/types.ts
Jira: [LIB-1456](https://fiscozen.atlassian.net/browse/LIB-1456)
> LIB-1456 feat(navbar): xmark icon when menu is open

- apps/storybook/package.json
- apps/storybook/src/stories/Input.stories.ts
- packages/icons/package.json
- packages/input/package.json
- packages/input/src/FzInput.vue
- packages/input/src/__tests__/FzInput.spec.ts
- packages/input/src/types.ts
- pnpm-lock.yaml
For Jira ticket: [LIB-992](https://fiscozen.atlassian.net/browse/LIB-992)
> feat(LIB): left and right click handler on FzInput

- packages/navbar/package.json
- packages/navbar/src/FzNavbar.vue
- pnpm-lock.yaml
Jira: [LIB-1475](https://fiscozen.atlassian.net/browse/LIB-1475)
Mobile flag was equal to <=1024. It should be <1024. LG breakpoint goes from 1024 onwards.
[LIB-1475]: https://fiscozen.atlassian.net/browse/LIB-1475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(LIB-1475): navbar correct mobile breakpoint

- packages/checkbox/package.json
- packages/checkbox/src/FzCheckbox.vue
- packages/checkbox/src/common.ts
Jira: [LIB-1459](https://fiscozen.atlassian.net/browse/LIB-1459)
> feat(LIB-1459): Update FzCheckbox design

- packages/dialog/package.json
- packages/dialog/src/FzDialog.vue
Jira: [LIB-1437](https://fiscozen.atlassian.net/browse/LIB-1437)
[LIB-1437]: https://fiscozen.atlassian.net/browse/LIB-1437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIB-1437 fix(dialog): center dialog vertically

- apps/storybook/src/stories/RadioGroup.stories.ts
- packages/radio/package.json
- packages/radio/src/FzRadioGroup.vue
- packages/radio/src/types.ts
FzRadioGroup default size to md
> FzRadioGroup default size to md

- apps/storybook/src/stories/form/Select.stories.ts
- packages/select/package.json
- packages/select/src/FzSelect.vue
- packages/select/src/components/FzSelectLabel.vue
- packages/select/src/components/FzSelectOption.vue
- packages/select/src/types.ts
Jira: [LIB-1452](https://fiscozen.atlassian.net/browse/LIB-1452)
[LIB-1452]: https://fiscozen.atlassian.net/browse/LIB-1452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(LIB-1452): FzSelectOption now supports a subtitle

- apps/storybook/src/stories/Layout.stories.ts
- packages/layout/package.json
- packages/layout/src/FzLayout.vue
- packages/layout/src/__tests__/FzLayout.spec.ts
- packages/layout/src/__tests__/__snapshots__/FzLayout.spec.ts.snap
- packages/layout/src/types.ts
- pnpm-lock.yaml
Jira: [LIB-1580](https://fiscozen.atlassian.net/browse/LIB-1580)
[LIB-1580]: https://fiscozen.atlassian.net/browse/LIB-1580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIB-1580 feat(layout): update to latest design

- apps/storybook/src/stories/panel/Card.stories.ts
- packages/card/package.json
- packages/card/src/FzCard.vue
- packages/card/src/__test__/FzCard.test.ts
- packages/card/src/types.ts
Add `hideHeader` props to hide the header of the card
> feat: Hide header props

- apps/storybook/src/stories/data/SimpleTable.stories.ts
- apps/storybook/src/stories/data/Table.stories.ts
- packages/simple-table/package.json
- packages/simple-table/src/FzSimpleTable.vue
- packages/simple-table/src/types.ts
- packages/table/package.json
- packages/table/src/FzTable.vue
- packages/table/src/types.ts
Jira: [LIB-1586](https://fiscozen.atlassian.net/browse/LIB-1586)
[LIB-1586]: https://fiscozen.atlassian.net/browse/LIB-1586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIB-1586 feat(table): column width support

- apps/storybook/src/stories/overlay/ViewFlag.stories.ts
- packages/view-flag/package.json
- packages/view-flag/src/FzViewFlag.vue
- packages/view-flag/src/__tests__/__snapshots__/FzViewFlag.spec.ts.snap
Jira: [LIB-1651](https://fiscozen.atlassian.net/browse/LIB-1651)
[LIB-1651]: https://fiscozen.atlassian.net/browse/LIB-1651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(LIB-1651): default slot for view flag

- .gitignore
- package.json
- pnpm-lock.yaml
Jira: [LIB-1691](https://fiscozen.atlassian.net/browse/LIB-1691)
[LIB-1691]: https://fiscozen.atlassian.net/browse/LIB-1691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(nx): update version

- packages/button/package.json
- packages/button/src/FzButton.vue
- packages/button/src/__tests__/FzButton.spec.ts
- packages/button/src/__tests__/__snapshots__/FzButton.spec.ts.snap
- packages/button/src/__tests__/__snapshots__/FzIconButtton.spec.ts.snap
Jira: [HD-11175](https://fiscozen.atlassian.net/browse/HD-11175)
Closes #216 
[HD-11175]: https://fiscozen.atlassian.net/browse/HD-11175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(#216): FzButton not showing icon when only iconName is set

- packages/layout/package.json
- packages/layout/src/FzLayout.vue
- packages/layout/src/types.ts
Jira: [LIB-1785](https://fiscozen.atlassian.net/browse/LIB-1785)
[LIB-1785]: https://fiscozen.atlassian.net/browse/LIB-1785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(FzLayout): fix width when not used in viewport mode

- apps/storybook/package.json
- apps/storybook/src/stories/navigation/Stepper.stories.ts
- packages/actionlist/src/FzActionlist.vue
- packages/actionlist/src/types.ts
- packages/dropdown/src/FzDropdown.vue
- packages/dropdown/src/types.ts
- packages/stepper/README.md
- packages/stepper/eslintrc.cjs
- packages/stepper/package.json
- packages/stepper/prettierrc.js
- packages/stepper/src/FzStepper.vue
- packages/stepper/src/__tests__/FzStepper.spec.ts
- packages/stepper/src/index.ts
- packages/stepper/src/types.ts
- packages/stepper/tsconfig.json
- packages/stepper/vite.config.ts
- packages/stepper/vitest.config.ts
- pnpm-lock.yaml
Jira: [LIB-1761](https://fiscozen.atlassian.net/browse/LIB-1761)
Ho lasciato indietro i test in quanto bisogna comunque migrare a quelli di cypress, se possibile farei in un secondo momento (cypress in locale mi sta dando problemi)
[LIB-1761]: https://fiscozen.atlassian.net/browse/LIB-1761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(stepper): initial implementation

- apps/storybook/src/stories/data/Table.stories.ts
- packages/collapse/src/FzCollapse.vue
- packages/collapse/src/types.ts
- packages/composables/src/composables/useMediaQuery.ts
- packages/dropdown/package.json
- packages/dropdown/src/FzIconDropdown.vue
- packages/progress/src/FzProgress.vue
- packages/simple-table/package.json
- packages/simple-table/src/FzColumn.vue
- packages/simple-table/src/types.ts
- packages/table/package.json
- packages/table/src/FzRow.vue
- packages/table/src/FzTable.cy.ts
- packages/table/src/FzTable.vue
- packages/table/src/types.ts
- packages/table/src/utils/index.ts
- pnpm-lock.yaml
Jira: [LIB-1762](https://fiscozen.atlassian.net/browse/LIB-1762)
[LIB-1762]: https://fiscozen.atlassian.net/browse/LIB-1762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIB-1762 feat(table): improved complete table

- apps/storybook/src/stories/data/Table.stories.ts
- packages/dropdown/package.json
- packages/dropdown/src/FzIconDropdown.vue
Jira: [LIB-2122](https://fiscozen.atlassian.net/browse/LIB-2122)
Per correggere il funzionamento delle action di FzTable quando usa la variante radio
[LIB-2122]: https://fiscozen.atlassian.net/browse/LIB-2122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(LIB-2122)

- packages/dropdown/package.json
- packages/dropdown/src/FzDropdown.vue
- packages/dropdown/src/types.ts
Add variant props to FzDropdown to handle FzButton variant
> feat: Button variant inside FzDropdown
